---
- name: "Deploy Leaf"
  hosts: "{{ HOST }}"
  gather_facts: no
  serial: 1
  connection: network_cli

  roles: 
    - ip_fabric/base
    - ip_fabric/vlans
  tags: deploy_leaf

- name: "Update Spines"
  hosts: spines
  gather_facts: no
  connection: network_cli

  roles:
    - ip_fabric/add_leaf_to_spine
  tags: update_spines