---
- name: ip_fabric_vlans - file check
  file:
    path: "./roles/ip_fabric/files/generated_vlans_{{ inventory_hostname }}.cfg"
    state: absent
  changed_when: no
  check_mode: no
  delegate_to: localhost

- name: ip_fabric_vlans - config generate
  template:
    src: ./roles/ip_fabric/templates/add_vlans.cfg
    dest: ./roles/ip_fabric/files/generated_vlans_{{ inventory_hostname }}.cfg
  delegate_to: localhost

- name: "Push vlans to leaf"
  nxos_config:
    src: ./roles/ip_fabric/files/generated_vlans_{{ inventory_hostname }}.cfg
  vars:
    ansible_command_timeout: 120
  tags: push_config
