---
- name: add_leaf_to_spine - file check
  file:
    path: "./roles/ip_fabric/files/generated_add_leaf_to_spine_{{ inventory_hostname }}.cfg"
    state: absent
  changed_when: no
  check_mode: no
  delegate_to: localhost

- name: add_leaf_to_spine - config generate
  template:
    src: ./roles/ip_fabric/templates/add_leaf_to_spine.cfg
    dest: ./roles/ip_fabric/files/generated_add_leaf_to_spine_{{ inventory_hostname }}.cfg
  delegate_to: localhost
